basePath: /
definitions:
  domain.NewsList:
    properties:
      description:
        description: TEXT
        type: string
      id:
        description: Поле id как SERIAL
        type: string
      link:
        description: VARCHAR(255) UNIQUE
        type: string
      publishedAt:
        description: TIMESTAMP
        type: string
      title:
        description: VARCHAR(255)
        type: string
    type: object
  router.errorResponse:
    properties:
      message:
        type: string
    type: object
  router.getNewsResponse:
    properties:
      currentPage:
        type: integer
      data:
        items:
          $ref: '#/definitions/domain.NewsList'
        type: array
      limit:
        type: integer
      totalCount:
        type: integer
      totalPages:
        type: integer
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for NewsApi Application
  title: News API
  version: "1.0"
paths:
  /news:
    get:
      consumes:
      - application/json
      description: get news
      parameters:
      - description: temp
        format: string
        in: query
        name: temp
        type: string
      - description: page
        format: number
        in: query
        name: page
        type: number
      - description: fromDate
        format: string
        in: query
        name: fromDate
        type: string
      - description: toDate
        format: string
        in: query
        name: toDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.getNewsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/router.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/router.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/router.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/router.errorResponse'
      summary: Get all news
      tags:
      - news
  /news/{id}:
    get:
      consumes:
      - application/json
      description: get news by id
      operationId: get-news-by-id
      parameters:
      - description: ID list
        in: path
        name: id
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.NewsList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/router.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/router.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/router.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/router.errorResponse'
      summary: Get news By ID
      tags:
      - news
swagger: "2.0"
